<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/3/15
 * Time: 7:08
 */

namespace app\libs\exception;

//自定义的异常输出
//从写 render 方法
use Exception;
use think\exception\Handle;
use think\Request;

class ExceptionHandler extends Handle
{
    protected $codes;

    public function render(Exception $e)
    {
        //此处 接收一个Exception 异常类，判断是否为我们自定义的一场
        if($e instanceof ParamException){
            //自定义的异常
            $result = [
                'msg' => $e->msg,
                'error_code' => $e->errorCode,
                'request_url' => Request::instance()->url()
            ];
            $this->codes = 400;

        }else{
            //其他异常
//            $result = [
//                'msg' => 'login suc!',
//                'error_code' => "100001",
//                'request_url' => Request::instance()->url()
//            ];
//            $this->codes = 401;
            return parent::render($e);
        }

        return json($result,$this->codes);
//        return parent::render($e); // TODO: Change the autogenerated stub
    }

    public function login(){
        //接收客户传来的  username pwd
    }
}